In [2]:
import numpy as np
import pandas as pd
import json 
import ast

In [3]:
df = pd.read_csv('SGJobData.CSV')
print(df.shape)

(1048585, 22)

In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048585 entries, 0 to 1048584
Data columns (total 22 columns):
 #   Column                              Non-Null Count    Dtype
---  ------                              --------------    -----
 0   categories                          1044597 non-null  object
 1   employmentTypes                     1044597 non-null  object
 2   metadata_expiryDate                 1044597 non-null  object
 3   metadata_isPostedOnBehalf           1048585 non-null  bool
 4   metadata_jobPostId                  1044597 non-null  object
 5   metadata_newPostingDate             1044597 non-null  object
 6   metadata_originalPostingDate        1044597 non-null  object
 7   metadata_repostCount                1048585 non-null  int64
 8   metadata_totalNumberJobApplication  1048585 non-null  int64
 9   metadata_totalNumberOfView          1048585 non-null  int64
 10  minimumYearsExperience              1048585 non-null  int64
 11  numberOfVacancies                   1048585 non-null  int64
 12  occupationId                        0 non-null        float64
 13  positionLevels                      1044597 non-null  object
 14  postedCompany_name                  1044597 non-null  object
 15  salary_maximum                      1048585 non-null  int64
 16  salary_minimum                      1048585 non-null  int64
 17  salary_type                         1044597 non-null  object
 18  status_id                           1048585 non-null  int64
 19  status_jobStatus                    1044597 non-null  object
 20  title                               1044597 non-null  object
 21  average_salary                      1048585 non-null  float64
dtypes: bool(1), float64(2), int64(8), object(11)
memory usage: 169.0+ MB
None

In [5]:
df.iloc[0:50000].to_excel('first 50k.xlsx')

In [6]:
df.columns

Index(['categories', 'employmentTypes', 'metadata_expiryDate',
       'metadata_isPostedOnBehalf', 'metadata_jobPostId',
       'metadata_newPostingDate', 'metadata_originalPostingDate',
       'metadata_repostCount', 'metadata_totalNumberJobApplication',
       'metadata_totalNumberOfView', 'minimumYearsExperience',
       'numberOfVacancies', 'occupationId', 'positionLevels',
       'postedCompany_name', 'salary_maximum', 'salary_minimum', 'salary_type',
       'status_id', 'status_jobStatus', 'title', 'average_salary'],
      dtype='object')

# Cleaning up steps #
1) Change to the appropriate data type
2) Remove truly blank roles
3) Remove duplicates if any.
4)

In [7]:
# Clean employmentTypes: drop null/blank rows, then inspect unique values
df['employmentTypes'] = df['employmentTypes'].astype('string').str.strip()
df = df[df['employmentTypes'].notna() & (df['employmentTypes'] != '')]

unique_employment_types = df['employmentTypes'].unique()
print(unique_employment_types)

<StringArray>
[            'Permanent',             'Full Time',             'Part Time',
              'Contract',             'Freelance',             'Temporary',
            'Flexi-work', 'Internship/Attachment']
Length: 8, dtype: string

In [8]:
df['employmentTypes'].value_counts(dropna=False)

Permanent                458139
Full Time                393352
Contract                 139182
Part Time                 25431
Temporary                 18241
Internship/Attachment      6959
Freelance                  2139
Flexi-work                 1154
Name: employmentTypes, dtype: Int64

In [9]:
df[df['employmentTypes'].isna() | (df['employmentTypes'].str.strip() == '')]

Empty DataFrame
Columns: [categories, employmentTypes, metadata_expiryDate, metadata_isPostedOnBehalf, metadata_jobPostId, metadata_newPostingDate, metadata_originalPostingDate, metadata_repostCount, metadata_totalNumberJobApplication, metadata_totalNumberOfView, minimumYearsExperience, numberOfVacancies, occupationId, positionLevels, postedCompany_name, salary_maximum, salary_minimum, salary_type, status_id, status_jobStatus, title, average_salary]
Index: []

[0 rows x 22 columns]

In [10]:
(df['employmentTypes'].isna() | (df['employmentTypes'].str.strip() == '')).sum()

0

In [11]:
df['metadata_totalNumberJobApplication'].value_counts(dropna=False)

0      656375
1      246159
2       23284
3       16627
4       12949
        ...
242         1
366         1
334         1
374         1
632         1
Name: metadata_totalNumberJobApplication, Length: 376, dtype: int64

In [12]:
categories_blank = df['categories'].isna() | (df['categories'].str.strip() == '')
employmentTypes_blank = df['employmentTypes'].isna() | (df['employmentTypes'].str.strip() == '')

print("categories blank count:", categories_blank.sum())
print("employmentTypes blank count:", employmentTypes_blank.sum())
print("both blank:", (categories_blank & employmentTypes_blank).sum())
print("categories blank but employmentTypes not:", (categories_blank & ~employmentTypes_blank).sum())
print("employmentTypes blank but categories not:", (~categories_blank & employmentTypes_blank).sum())
print("same rows (masks identical):", categories_blank.equals(employmentTypes_blank))

categories blank count: 0
employmentTypes blank count: 0
both blank: 0
categories blank but employmentTypes not: 0
employmentTypes blank but categories not: 0
same rows (masks identical): False

# Remove empty rows # (df1)

In [13]:
df1 = df[df['categories'].notna() & (df['categories'].str.strip() != '')].drop(columns=['occupationId'])
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1044597 entries, 0 to 1048584
Data columns (total 21 columns):
 #   Column                              Non-Null Count    Dtype
---  ------                              --------------    -----
 0   categories                          1044597 non-null  object
 1   employmentTypes                     1044597 non-null  string
 2   metadata_expiryDate                 1044597 non-null  object
 3   metadata_isPostedOnBehalf           1044597 non-null  bool
 4   metadata_jobPostId                  1044597 non-null  object
 5   metadata_newPostingDate             1044597 non-null  object
 6   metadata_originalPostingDate        1044597 non-null  object
 7   metadata_repostCount                1044597 non-null  int64
 8   metadata_totalNumberJobApplication  1044597 non-null  int64
 9   metadata_totalNumberOfView          1044597 non-null  int64
 10  minimumYearsExperience              1044597 non-null  int64
 11  numberOfVacancies                   1044597 non-null  int64
 12  positionLevels                      1044597 non-null  object
 13  postedCompany_name                  1044597 non-null  object
 14  salary_maximum                      1044597 non-null  int64
 15  salary_minimum                      1044597 non-null  int64
 16  salary_type                         1044597 non-null  object
 17  status_id                           1044597 non-null  int64
 18  status_jobStatus                    1044597 non-null  object
 19  title                               1044597 non-null  object
 20  average_salary                      1044597 non-null  float64
dtypes: bool(1), float64(1), int64(8), object(10), string(1)
memory usage: 168.4+ MB
None

# Check for duplicates (if any) - but first change data type to the right ones #

In [14]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1044597 entries, 0 to 1048584
Data columns (total 21 columns):
 #   Column                              Non-Null Count    Dtype
---  ------                              --------------    -----
 0   categories                          1044597 non-null  object
 1   employmentTypes                     1044597 non-null  string
 2   metadata_expiryDate                 1044597 non-null  object
 3   metadata_isPostedOnBehalf           1044597 non-null  bool
 4   metadata_jobPostId                  1044597 non-null  object
 5   metadata_newPostingDate             1044597 non-null  object
 6   metadata_originalPostingDate        1044597 non-null  object
 7   metadata_repostCount                1044597 non-null  int64
 8   metadata_totalNumberJobApplication  1044597 non-null  int64
 9   metadata_totalNumberOfView          1044597 non-null  int64
 10  minimumYearsExperience              1044597 non-null  int64
 11  numberOfVacancies                   1044597 non-null  int64
 12  positionLevels                      1044597 non-null  object
 13  postedCompany_name                  1044597 non-null  object
 14  salary_maximum                      1044597 non-null  int64
 15  salary_minimum                      1044597 non-null  int64
 16  salary_type                         1044597 non-null  object
 17  status_id                           1044597 non-null  int64
 18  status_jobStatus                    1044597 non-null  object
 19  title                               1044597 non-null  object
 20  average_salary                      1044597 non-null  float64
dtypes: bool(1), float64(1), int64(8), object(10), string(1)
memory usage: 168.4+ MB

In [15]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1044597 entries, 0 to 1048584
Data columns (total 21 columns):
 #   Column                              Non-Null Count    Dtype
---  ------                              --------------    -----
 0   categories                          1044597 non-null  object
 1   employmentTypes                     1044597 non-null  string
 2   metadata_expiryDate                 1044597 non-null  object
 3   metadata_isPostedOnBehalf           1044597 non-null  bool
 4   metadata_jobPostId                  1044597 non-null  object
 5   metadata_newPostingDate             1044597 non-null  object
 6   metadata_originalPostingDate        1044597 non-null  object
 7   metadata_repostCount                1044597 non-null  int64
 8   metadata_totalNumberJobApplication  1044597 non-null  int64
 9   metadata_totalNumberOfView          1044597 non-null  int64
 10  minimumYearsExperience              1044597 non-null  int64
 11  numberOfVacancies                   1044597 non-null  int64
 12  positionLevels                      1044597 non-null  object
 13  postedCompany_name                  1044597 non-null  object
 14  salary_maximum                      1044597 non-null  int64
 15  salary_minimum                      1044597 non-null  int64
 16  salary_type                         1044597 non-null  object
 17  status_id                           1044597 non-null  int64
 18  status_jobStatus                    1044597 non-null  object
 19  title                               1044597 non-null  object
 20  average_salary                      1044597 non-null  float64
dtypes: bool(1), float64(1), int64(8), object(10), string(1)
memory usage: 168.4+ MB

In [16]:
print("duplicate jobPostIds:", df1['metadata_jobPostId'].duplicated().sum())
df1[df1['metadata_jobPostId'].duplicated(keep=False)].sort_values('metadata_jobPostId')

duplicate jobPostIds: 0

Empty DataFrame
Columns: [categories, employmentTypes, metadata_expiryDate, metadata_isPostedOnBehalf, metadata_jobPostId, metadata_newPostingDate, metadata_originalPostingDate, metadata_repostCount, metadata_totalNumberJobApplication, metadata_totalNumberOfView, minimumYearsExperience, numberOfVacancies, positionLevels, postedCompany_name, salary_maximum, salary_minimum, salary_type, status_id, status_jobStatus, title, average_salary]
Index: []

[0 rows x 21 columns]

In [17]:
import json

df1['categories_parsed'] = df1['categories'].apply(json.loads)
df1['categories_parsed'].head().to_excel('categories_parsed check.xlsx')

In [18]:
df_categories = df1[['metadata_jobPostId', 'categories_parsed']].explode('categories_parsed')
df_categories = df_categories.dropna(subset=['categories_parsed'])
df_categories['category_id'] = df_categories['categories_parsed'].apply(lambda d: d['id'])
df_categories['category'] = df_categories['categories_parsed'].apply(lambda d: d['category'])
df_categories = df_categories.drop(columns='categories_parsed')

df_categories.head()

  metadata_jobPostId  category_id                     category
0   MCF-2023-0252866           13         Environment / Health
0   MCF-2023-0252866           25                Manufacturing
0   MCF-2023-0252866           36  Sciences / Laboratory / R&D
1   MCF-2023-0273977           21       Information Technology
2   MCF-2023-0273994           33       Repair and Maintenance

In [19]:
def parse_json(val):
    if isinstance(val, str):
        return json.loads(val)
    return val

In [20]:
records = df1['categories'].apply(parse_json).explode()
result_df = pd.json_normalize(records)[['id', 'category']]
result_df = result_df.drop_duplicates(subset='id').reset_index(drop=True)
result_df.head()

   id                     category
0  13         Environment / Health
1  25                Manufacturing
2  36  Sciences / Laboratory / R&D
3  21       Information Technology
4  33       Repair and Maintenance

In [21]:
result_df.to_excel('categories metadata.xlsx')

In [22]:
result_df = result_df.drop_duplicates(subset='id').reset_index(drop=True)
result_df

    id                           category
0   13               Environment / Health
1   25                      Manufacturing
2   36        Sciences / Laboratory / R&D
3   21             Information Technology
4   33             Repair and Maintenance
5    2                Admin / Secretarial
6    7                         Consulting
7   29              Professional Services
8   37         Security and Investigation
9    1   Accounting / Auditing / Taxation
10  24           Logistics / Supply Chain
11  35                     Sales / Retail
12  14                Events / Promotions
13  11                        Engineering
14  39                 Telecommunications
15  43              Precision Engineering
16  15                                F&B
17   4     Architecture / Interior Design
18   6          Building and Construction
19  41                             Others
20   3                Advertising / Media
21   9                             Design
22  26       Marketing / Public Relations
23   8                   Customer Service
24  32  Real Estate / Property Management
25  16                 General Management
26  17                       General Work
27   5                Banking and Finance
28  42                    Wholesale Trade
29  31         Purchasing / Merchandising
30  34                    Risk Management
31  27         Medical / Therapy Services
32  20                    Human Resources
33  23                              Legal
34  28             Personal Care / Beauty
35  10             Education and Training
36  18        Healthcare / Pharmaceutical
37  22                          Insurance
38  38                    Social Services
39  30             Public / Civil Service
40  19                        Hospitality
41  12                      Entertainment
42  40                   Travel / Tourism

In [23]:
len(result_df)

43

In [24]:
result_df.to_excel('categories meta.xlsx')

In [25]:
if isinstance(df1['categories'].iloc[0], str):
    df1['categories'] = df1['categories'].apply(ast.literal_eval)

# Step 2: explode so each category dict gets its own row
df_map = df1[['metadata_jobPostId', 'categories']].explode('categories').reset_index(drop=True)

# Step 3: pull out the 'id' (and optionally 'category' name) from each dict
df_map['category_id'] = df_map['categories'].apply(lambda x: x['id'])
df_map['category_name'] = df_map['categories'].apply(lambda x: x['category'])

# Step 4: drop the now-unneeded dict column
df_map = df_map.drop(columns=['categories'])
df_map

,metadata_jobPostId,category_id,category_name
0,MCF-2023-0252866,13,Environment / Health
1,MCF-2023-0252866,25,Manufacturing
2,MCF-2023-0252866,36,Sciences / Laboratory / R&D
3,MCF-2023-0273977,21,Information Technology
4,MCF-2023-0273994,33,Repair and Maintenance
...,...,...,...
1767824,RANDOM_JOB_20251115011349636339_9,2,Admin / Secretarial
1767825,RANDOM_JOB_20251115011349636339_9,8,Customer Service
1767826,RANDOM_JOB_20251115011349636339_9,19,Hospitality
1767827,RANDOM_JOB_20251115011349636339_9,27,Medical / Therapy Services
1767828,RANDOM_JOB_20251115011349636339_9,35,Sales / Retail

In [26]:
df1[df1['metadata_jobPostId'] == "RANDOM_JOB_20251115011349636339_9"]

,categories,employmentTypes,metadata_expiryDate,metadata_isPostedOnBehalf,metadata_jobPostId,metadata_newPostingDate,metadata_originalPostingDate,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,...,positionLevels,postedCompany_name,salary_maximum,salary_minimum,salary_type,status_id,status_jobStatus,title,average_salary,categories_parsed
1048584,"[{'id': 2, 'category': 'Admin / Secretarial'},...",Permanent,2024-04-21,False,RANDOM_JOB_20251115011349636339_9,2023-11-18,2023-10-28,2,632,3920,...,Non-executive,THALES DIS (SINGAPORE) PTE. LTD.,14420727,164428,Monthly,0,Re-open,sales and operations manager,7292577.5,"[{'id': 2, 'category': 'Admin / Secretarial'},..."

In [27]:
14420727/1e6

14.420727

In [28]:
df1['positionLevels'].value_counts(dropna=False)

Executive            253701
Junior Executive     167656
Non-executive        131608
Fresh/entry level    118661
Professional         112208
Manager              110122
Senior Executive     100459
Middle Management     27375
Senior Management     22807
Name: positionLevels, dtype: int64